version: '3'

services:
  # backend service
  backend:
    build:
      context: ./backend
    depends_on:
      - postgres
    init: true
    ports:
      - 3000:3000

  # frontend service
  frontend:
    build:
      context: ./frontend
    depends_on:
      - backend
    ports:
      - 8080:8080

  # postgres service
  postgres:
    build:
      context: ./postgres
    environment:
      - POSTGRES_PASSWORD=password
    ports:
      - 5432:5432
    volumes:
      - data:/var/lib/postgresql/data

volumes:
  data:
