version: '3'

services:
  app:
    build: .
    depends_on:
      - db
    init: true
    ports:
      - 3000:3000
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=password
    ports:
      - 5432:5432
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
