version: '3'

services:
  # backend service
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.lint
    command: bash -c "cargo fmt && cargo clippy"
    volumes:
      - ./backend/src:/app/src

  # frontend service
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.lint
    command: npm run lint
    volumes:
      - ./frontend/src:/app/src
