version: '3'

services:
  app:
    build:
      context: .
      target: build-backend
    command: cargo test -- --test-threads=1
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=password
    ports:
      - 5432:5432
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
