FROM rust:1.57.0
WORKDIR /app
RUN apt-get update && apt-get install -y libssl-dev
RUN cargo install cargo-watch
RUN cargo init
COPY Cargo.toml Cargo.lock ./
RUN cargo build
COPY . .
RUN touch src/main.rs && cargo build
